steps:
  deploy:
    image: node:22-alpine
    commands:
      - apk add rsync
      - rsync -av /woodpecker/src/ $REPO_PATH
      - npm ci
      - npm run build
      - pm2 restart custardbot
    when:
      branch: main