steps:
  deploy:
    image: node:22-alpine
    commands:
      - apk add rsync
      - rsync -av /woodpecker/src/github.com/SucculentGoose/custardbot/ $REPO_PATH/
      - cd $REPO_PATH
      - npm ci && npm run build
      - npm install -g pm2
      - pm2 trigger custardbot reload # Graceful host reload!
    when:
      branch: main
