steps:
  deploy:
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
      REPO_PATH:
        from_secret: repo_path
        commands:
          # Debug source
          - ls -la /woodpecker/src/github.com/SucculentGoose/custardbot/ | head -10
          - ls -la /woodpecker/src/github.com/SucculentGoose/custardbot/package*.json ecosystem*.js || echo "Source files missing"

          # Rsync source only (no excludes first)
          - /usr/bin/rsync -avz --delete -e "ssh -o StrictHostKeyChecking=accept-new" /woodpecker/src/github.com/SucculentGoose/custardbot/ $SSH_USER@$SSH_HOST:$REPO_PATH/

          # Debug remote
          - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "ls -la $REPO_PATH/package*.json $REPO_PATH/ecosystem*.js || echo 'Remote files missing'"

          # NPM + PM2
          - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'export PATH="$HOME/.local/share/fnm:$PATH" && eval "$("$HOME/.local/share/fnm/fnm" env --use-on-cd)" && cd $REPO_PATH && npm ci && npx pm2 reload custardbot || npx pm2 start ecosystem.config.js --env production'
    when:
      branch: main
