steps:
  deploy:
    image: node:22-alpine
    commands:
      - apk add rsync
      - rsync -av /woodpecker/src/github.com/SucculentGoose/custardbot/ $REPO_PATH/
      - cd $REPO_PATH
      - npm ci
      - npm run build
      - npm install pm2 -g     # Pipeline-local PM2
      - pm2 restart custardbot --no-daemon  # Controls host via cwd
    when:
      branch: main