steps:
  deploy:
    image: alpine:latest  # Smaller, full openssh
    secrets: [ssh_key, ssh_host, ssh_user, repo_path]
    commands:
      - apk add --no-cache rsync openssh-client
      - mkdir -p ~/.ssh && chmod 700 ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa  # UPPERCASE!
      - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts  # No -H
      - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" /woodpecker/src/github.com/SucculentGoose/custardbot/ $SSH_USER@$SSH_HOST:$REPO_PATH/
      - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $REPO_PATH && pm2 reload custardbot"
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
      REPO_PATH:
        from_secret: repo_path
    when:
      branch: main