steps:
  deploy:
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
      REPO_PATH:
        from_secret: repo_path
    commands:
          - apk add --no-cache rsync openssh-client
    
          - mkdir -p ~/.ssh && chmod 700 ~/.ssh
          - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
    
          - echo "REPO_PATH=[$REPO_PATH] SSH_USER=[$SSH_USER] SSH_HOST=[$SSH_HOST]"
    
          # Test SSH connection
          - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes $SSH_USER@$SSH_HOST "echo 'SSH OK'"
    
          # Clear and mkdir REPO_PATH
          - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes $SSH_USER@$SSH_HOST "rm -rf $REPO_PATH/* $REPO_PATH/.* 2>/dev/null || true; mkdir -p $REPO_PATH"
    
          # Rsync all files
          - rsync -avz --delete --exclude='node_modules/' --exclude='.git/' /woodpecker/src/github.com/SucculentGoose/custardbot/ $SSH_USER@$SSH_HOST:$REPO_PATH/ -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes"
    
          - ls -la /woodpecker/src/github.com/SucculentGoose/custardbot/
    
          # Install and PM2
          - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes $SSH_USER@$SSH_HOST "cd $REPO_PATH && ls -la package.json ecosystem.config.js && npm ci --production && npx pm2 reload custardbot || npx pm2 start ecosystem.config.js --env production"

    when:
      branch: main
