steps:
  deploy:
    image: alpine:latest
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
      REPO_PATH:
        from_secret: repo_path
    commands:
          - apk add --no-cache rsync openssh-client bash
    
          - mkdir -p ~/.ssh && chmod 700 ~/.ssh
          - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    
          # Debug vars
          - echo "REPO_PATH=[$REPO_PATH] SSH_USER=[$SSH_USER] SSH_HOST=[$SSH_HOST]"
    
          - REPO_PATH=${REPO_PATH:-/home/$SSH_USER/custardbot}
    
          # Test SSH key + setup authorized_keys if needed (one-time)
          - |
            ssh -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=~/.ssh/known_hosts \
              -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -i ~/.ssh/id_rsa \
              $SSH_USER@$SSH_HOST "echo 'SSH key test OK' && mkdir -p ~/.ssh && chmod 700 ~/.ssh || echo "SSH failed - check key in server ~/.ssh/authorized_keys for $SSH_USER (chmod 600/700)"
    
          # Now safe rm/mkdir
          - ssh -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=~/.ssh/known_hosts -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "rm -rf '$REPO_PATH'/* '$REPO_PATH'/.[^.]* 2>/dev/null || true ; mkdir -p '$REPO_PATH' && chmod 755 '$REPO_PATH'"
    
          # Rsync with RSA fix
          - /usr/bin/rsync -avz --delete --exclude='node_modules/' --exclude='.git/' --ignore-times --size-only --checksum --rsync-path="sudo rsync" -e "ssh -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=~/.ssh/known_hosts -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -i ~/.ssh/id_rsa" /woodpecker/src/github.com/SucculentGoose/custardbot/ $SSH_USER@$SSH_HOST:$REPO_PATH/
    
          - ls -la /woodpecker/src/github.com/SucculentGoose/custardbot/
    
          # Final deploy
          - |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=~/.ssh/known_hosts \
              -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -i ~/.ssh/id_rsa \
              $SSH_USER@$SSH_HOST \
              "cd '$REPO_PATH' && pwd && ls -la package*.json ecosystem*.js && npm ci --production && npx pm2 reload custardbot || npx pm2 start ecosystem.config.js --env production"
    when:
      branch: main
